services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.35.0
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config:/etc/prometheus/config
    command:
      - '--config.file=/etc/prometheus/config/prometheus.yml'
  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug
